### ISSUE TITLE
error: cannot find symbol: class FlutterGooglePlacesSdkPlugin

### ISSUE THREAD

**Issue by mauriziopinotti** [matanshukry/flutter_google_places_sdk#131]
This error started happening with version `0.4.3`, it used to work with `0.4.2+1`:

```
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileLocalDebugJavaWithJavac'.
[        ] > Compilation failed; see the compiler output below.
[        ]   /***/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:64: error: cannot find symbol
[        ]         flutterEngine.getPlugins().add(new com.msh.flutter_google_places_sdk.FlutterGooglePlacesSdkPlugin());
[        ]                                                                             ^
[        ]     symbol:   class FlutterGooglePlacesSdkPlugin
[        ]     location: package com.msh.flutter_google_places_sdk
[        ]   1 error
[        ] * Try:
[        ] > Check your code and dependencies to fix the compilation error(s)
[        ] > Run with --scan to get full insights.
[        ] * Exception is:
[        ] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileLocalDebugJavaWithJavac'.
[        ] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:130)
[        ] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:293)
[        ] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:128)
[        ] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:116)
[        ] 	at org.gradle.api.internal.tasks.execution.ProblemsTaskPathTrackingTaskExecuter.execute(ProblemsTaskPathTrackingTaskExecuter.java:40)
[        ] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
[        ] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
[        ] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
[        ] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
[        ] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
[        ] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
[        ] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
[        ] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:210)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:205)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:67)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:60)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:167)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:60)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:54)
[        ] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
[        ] 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
[        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
[        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
[        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
[        ] 	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:85)
[        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
[        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
[        ] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:459)
[        ] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:376)
[        ] 	at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:111)
[        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.executeWithServices(DefaultTaskExecutionGraph.java:138)
[        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:123)
[        ] 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:35)
[        ] 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:51)
[        ] 	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:54)
[        ] 	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:43)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:210)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:205)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:67)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:60)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:167)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:60)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:54)
[        ] 	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor.execute(BuildOperationFiringBuildWorkerExecutor.java:40)
[        ] 	at org.gradle.internal.build.DefaultBuildLifecycleController.lambda$executeTasks$10(DefaultBuildLifecycleController.java:313)
[        ] 	at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:266)
[        ] 	at org.gradle.internal.model.StateTransitionController.lambda$tryTransition$8(StateTransitionController.java:177)
[        ] 	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:46)
[        ] 	at org.gradle.internal.model.StateTransitionController.tryTransition(StateTransitionController.java:177)
[        ] 	at org.gradle.internal.build.DefaultBuildLifecycleController.executeTasks(DefaultBuildLifecycleController.java:304)
[        ] 	at org.gradle.internal.build.DefaultBuildWorkGraphController$DefaultBuildWorkGraph.runWork(DefaultBuildWorkGraphController.java:220)
[        ] 	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:263)
[        ] 	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:127)
[        ] 	at org.gradle.composite.internal.DefaultBuildController.doRun(DefaultBuildController.java:181)
[        ] 	at org.gradle.composite.internal.DefaultBuildController.access$000(DefaultBuildController.java:50)
[        ] 	at org.gradle.composite.internal.DefaultBuildController$BuildOpRunnable.lambda$run$0(DefaultBuildController.java:198)
[        ] 	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:85)
[        ] 	at org.gradle.composite.internal.DefaultBuildController$BuildOpRunnable.run(DefaultBuildController.java:198)
[        ] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[        ] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[        ] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[        ] 	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
[        ] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[        ] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[        ] 	at java.base/java.lang.Thread.run(Thread.java:840)
[        ] Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler output below.
[        ] /***/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:64: error: cannot find symbol
[        ]       flutterEngine.getPlugins().add(new com.msh.flutter_google_places_sdk.FlutterGooglePlacesSdkPlugin());
[        ]                                                                           ^
[        ]   symbol:   class FlutterGooglePlacesSdkPlugin
[        ]   location: package com.msh.flutter_google_places_sdk
```

**Comment by matanshukry** [comment]
@mauriziopinotti 0.2.2 had various issues and should not be used.
If you can also try the latest version - 0.3.0.

**Comment by mauriziopinotti** [comment]
So, it should probably be fixed here: https://github.com/matanshukry/flutter_google_places_sdk/blob/master/flutter_google_places_sdk/pubspec.yaml as the current flutter_google_places_sdk depends on `flutter_google_places_sdk_android: ^0.2.2`

**Comment by matanshukry** [comment]
@mauriziopinotti That is the endorsing package and it cannot be updated until the iOS implementation is done.
Hence I recommend doing the override manually until then

**Comment by mauriziopinotti** [comment]
Apps usually depend on the main package only, they should not override platform-specific deps.
So maybe you shouldn't have released the new package until all platforms were ready, should you?

Btw, I don't see any problem in releasing a new `flutter_google_places_sdk` version that only bumps the android version, do you see any?

**Comment by matanshukry** [comment]
> Btw, I don't see any problem in releasing a new flutter_google_places_sdk version that only bumps the android version, do you see any?

The platform-interface version has breaking changes. the android depends on the newer, while the iOS on lower.
When using overrides it seems to work, but without it the `flutter pub get` fails

> So maybe you shouldn't have released the new package until all platforms were ready, should you?

That's not how flutter plugins work.
If you do not release new package until all platforms work, you can not release anything. there is no way to do it in 1 step.
With plugins, you release platform-by-platform.

If you prefer to wait, feel free to do so.
Closing since resolved.

**Comment by mauriziopinotti** [comment]
> That's not how flutter plugins work. If you do not release new package until all platforms work, you can not release anything. there is no way to do it in 1 step. With plugins, you release platform-by-platform.
> 
> If you prefer to wait, feel free to do so. Closing since resolved.

This is not correct: in a federated plugin, updating a single platform implementation is possible as long as it targets the same platform_interface version.

The real issue is compatibility:
- flutter_google_places_sdk_android 0.3.0 requires flutter_google_places_sdk_platform_interface ^0.4.0
- flutter_google_places_sdk 0.4.3 depends on flutter_google_places_sdk_platform_interface 0.3.x
So 0.3.0 cannot be used with 0.4.3.

However, flutter_google_places_sdk_android 0.2.3 is compatible with the current platform interface and fixes the Android issues present in 0.2.2

The problem is simply that 0.2.3 is not referenced upstream, forcing users to rely on dependency_overrides.

**The correct fix is to update the main plugin to depend on flutter_google_places_sdk_android ^0.2.3, rather than saying a single-platform update is impossible.**

**Comment by ParthAlliancetek** [comment]
@mauriziopinotti  have you found a solution?
I am experiencing the same issue in my pub.spec.yaml file.

dependencies:
  flutter_google_places_sdk: ^0.4.3
dependency_overrides:
  flutter_google_places_sdk_android: ^0.2.2

**Comment by ParthAlliancetek** [comment]
@matanshukry I would appreciate it if you could provide a solution for this issue as it is only occurring on Android.

**Comment by mauriziopinotti** [comment]
> [@mauriziopinotti](https://github.com/mauriziopinotti) have you found a solution? I am experiencing the same issue in my pub.spec.yaml file.
> 
> dependencies: flutter_google_places_sdk: ^0.4.3 dependency_overrides: flutter_google_places_sdk_android: ^0.2.2

I have overridden my dependencies with the versions that used to work before the plugin update:

```yaml
dependency_overrides:
  # Waiting for https://github.com/matanshukry/flutter_google_places_sdk/issues/131
  flutter_google_places_sdk: 0.4.2+1
  flutter_google_places_sdk_platform_interface: 0.3.4
  flutter_google_places_sdk_ios: 0.2.0
  flutter_google_places_sdk_web: 0.2.2
  flutter_google_places_sdk_android: 0.2.1
```

The versions will be rolled back once the iOS version is compatible with the new interface.

**Comment by ParthAlliancetek** [comment]
> > [@mauriziopinotti](https://github.com/mauriziopinotti) have you found a solution? I am experiencing the same issue in my pub.spec.yaml file.
> > dependencies: flutter_google_places_sdk: ^0.4.3 dependency_overrides: flutter_google_places_sdk_android: ^0.2.2
> 
> I have overridden my dependencies with the versions that used to work before the plugin update:
> 
> dependency_overrides:
>   # Waiting for https://github.com/matanshukry/flutter_google_places_sdk/issues/131
>   flutter_google_places_sdk: 0.4.2+1
>   flutter_google_places_sdk_platform_interface: 0.3.4
>   flutter_google_places_sdk_ios: 0.2.0
>   flutter_google_places_sdk_web: 0.2.2
>   flutter_google_places_sdk_android: 0.2.1
> The versions will be rolled back once the iOS version is compatible with the new interface.

Thank you , worked for me 👍

**Comment by mauriziopinotti** [comment]
@matanshukry so can we please reopen this, as it's not completed yet?

**Comment by ParthAlliancetek** [comment]
@matanshukry  @mauriziopinotti  is right!
We are still experiencing issues even after downgrading the version. This also applies to the search places API.

Please investigate the matter.

**Comment by mauriziopinotti** [comment]
Looks like the maintainer of this project is not really maintaining it... 😢
